export const SUPPORTED_LOCALES=["en-US","es-ES","fr-FR","de-DE","pt-BR","zh-CN","ja-JP","ko-KR"] as const;
export type SupportedLocale=(typeof SUPPORTED_LOCALES)[number];
type K="cmms.confirm.title"|"cmms.confirm.warning"|"cmms.confirm.approve"|"cmms.confirm.reject"|"cmms.field.title"|"cmms.field.description"|"cmms.field.priority"|"cmms.field.asset";
const EN:Record<K,string>={"cmms.confirm.title":"Review before sending to the maintenance system","cmms.confirm.warning":"WrenchRelay will not write this record until an authenticated technician approves this exact payload.","cmms.confirm.approve":"Approve and allow dispatch","cmms.confirm.reject":"Reject","cmms.field.title":"Title","cmms.field.description":"Description","cmms.field.priority":"Priority","cmms.field.asset":"Asset"};
const MATRIX:Record<SupportedLocale,Record<K,string>>={
"en-US":EN,
"es-ES":{"cmms.confirm.title":"Revise antes de enviar al sistema de mantenimiento","cmms.confirm.warning":"WrenchRelay no escribirá este registro hasta que un técnico autenticado apruebe exactamente esta carga útil.","cmms.confirm.approve":"Aprobar y permitir el envío","cmms.confirm.reject":"Rechazar","cmms.field.title":"Título","cmms.field.description":"Descripción","cmms.field.priority":"Prioridad","cmms.field.asset":"Activo"},
"fr-FR":{"cmms.confirm.title":"Vérifier avant l’envoi au système de maintenance","cmms.confirm.warning":"WrenchRelay n’écrira pas cet enregistrement tant qu’un technicien authentifié n’aura pas approuvé cette charge utile exacte.","cmms.confirm.approve":"Approuver et autoriser l’envoi","cmms.confirm.reject":"Rejeter","cmms.field.title":"Titre","cmms.field.description":"Description","cmms.field.priority":"Priorité","cmms.field.asset":"Équipement"},
"de-DE":{"cmms.confirm.title":"Vor dem Senden an das Instandhaltungssystem prüfen","cmms.confirm.warning":"WrenchRelay schreibt diesen Datensatz erst, wenn ein authentifizierter Techniker genau diese Nutzlast freigibt.","cmms.confirm.approve":"Freigeben und Versand erlauben","cmms.confirm.reject":"Ablehnen","cmms.field.title":"Titel","cmms.field.description":"Beschreibung","cmms.field.priority":"Priorität","cmms.field.asset":"Anlage"},
"pt-BR":{"cmms.confirm.title":"Revise antes de enviar ao sistema de manutenção","cmms.confirm.warning":"O WrenchRelay não gravará este registro até que um técnico autenticado aprove exatamente esta carga.","cmms.confirm.approve":"Aprovar e permitir o envio","cmms.confirm.reject":"Rejeitar","cmms.field.title":"Título","cmms.field.description":"Descrição","cmms.field.priority":"Prioridade","cmms.field.asset":"Ativo"},
"zh-CN":{"cmms.confirm.title":"发送到维护系统前请审核","cmms.confirm.warning":"只有经过身份验证的技术人员批准完全相同的数据后，WrenchRelay 才会写入该记录。","cmms.confirm.approve":"批准并允许发送","cmms.confirm.reject":"拒绝","cmms.field.title":"标题","cmms.field.description":"说明","cmms.field.priority":"优先级","cmms.field.asset":"资产"},
"ja-JP":{"cmms.confirm.title":"保全システムへ送信する前に確認してください","cmms.confirm.warning":"認証済みの技術者がこの正確なペイロードを承認するまで、WrenchRelay はレコードを書き込みません。","cmms.confirm.approve":"承認して送信を許可","cmms.confirm.reject":"却下","cmms.field.title":"件名","cmms.field.description":"説明","cmms.field.priority":"優先度","cmms.field.asset":"設備"},
"ko-KR":{"cmms.confirm.title":"유지보수 시스템으로 보내기 전에 검토하세요","cmms.confirm.warning":"인증된 기술자가 이 정확한 페이로드를 승인하기 전에는 WrenchRelay가 기록을 쓰지 않습니다.","cmms.confirm.approve":"승인하고 전송 허용","cmms.confirm.reject":"거부","cmms.field.title":"제목","cmms.field.description":"설명","cmms.field.priority":"우선순위","cmms.field.asset":"자산"}};
export function resolveLocale(locale:string):SupportedLocale{const exact=SUPPORTED_LOCALES.find(c=>c.toLowerCase()===locale.toLowerCase());if(exact)return exact;const language=locale.split("-")[0]?.toLowerCase();return SUPPORTED_LOCALES.find(c=>c.toLowerCase().startsWith(`${language}-`))??"en-US";}
export function t(locale:string,key:K):string{const resolved=resolveLocale(locale);return MATRIX[resolved][key]??EN[key];}
export function translationMatrix(locale:string):Record<K,string>{return MATRIX[resolveLocale(locale)];}
